openapi: 3.0.3
info:
  title: XGUserServer
  description: Go microservice that handles registered users
  version: 0.0.1
  contact:
    name: Edson Manuel Carballo Vera
    email: edsonmanuelcarballovera@xatal.com.mx
    url: 'https://twitter.com/EdsonManuelVera'
paths:
  /user:
    summary: User catalog
    description: Catalog containing user related actions
    post:
      summary: Registers a new user
      description: Creates a new user on the system with the given information
      requestBody:
        description: Information needed to create a new user
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: Email of the user
                  minLength: 5
                  maxLength: 320
                  example: email@email.com
                password:
                  type: string
                  description: Password of the user
                  minLength: 8
                  maxLength: 100
                  example: g00dP4ssw0rD
      responses:
        '201':
          description: The user has been registered
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - email
                  - password
                properties:
                  id:
                    type: integer
                    description: Id of the user
                    minimum: 1
                    example: 25
                  email:
                    type: string
                    description: Email of the user
                    minLength: 5
                    maxLength: 320
                    example: email@email.com
                  password:
                    type: string
                    description: Password of the user
                    minLength: 8
                    maxLength: 100
                    example: g00dP4ssw0rD
        '400':
          description: The request is wrong or malformed
        '406':
          description: The given information is not acceptable
        '409':
          description: The given email is already registered
        '500':
          description: An internal error has occurred. Contact maintainer
