openapi: 3.0.3
info:
  title: XGUserServer
  description: Go microservice that handles registered users
  version: 0.0.2
  contact:
    name: Edson Manuel Carballo Vera
    email: edsonmanuelcarballovera@xatal.com.mx
    url: https://twitter.com/EdsonManuelVera
servers:
  - url: 'http://clayrite.ddns.net:42100'
components:
  schemas:
    anonymousUser:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: Email of the user
          minLength: 5
          maxLength: 320
          example: email@email.com
        password:
          type: string
          description: Password of the user
          minLength: 8
          maxLength: 100
          example: g00dP4ssw0rD
    identifiedUser:
      allOf:
        - $ref: '#/components/schemas/anonymousUser'
      required:
        - id
      properties:
        id:
          type: integer
          description: Numeric identifier of the user
          minimum: 1
          example: 24
paths:
  /user:
    summary: User catalog
    description: Catalog containing user related actions
    post:
      tags:
        - User
      summary: Registers a new user
      description: Creates a new user on the system with the given information
      requestBody:
        description: Information needed to create a new user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anonymousUser'
      responses:
        201:
          description: The user has been registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/identifiedUser'
        400:
          description: The request is wrong or malformed
        406:
          description: The given information is not acceptable
        409:
          description: The given email is already registered
        500:
          description: An internal error has occurred. Contact maintainer
  /user/login:
    post:
      tags:
        - User
      summary: User autenticates against the service
      description: Tries to log in with an email and password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anonymousUser'
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/identifiedUser'
        400:
          description: The request is wrong or malformed
        404:
          description: Login unsuccessful. Wrong credentials
        406:
          description: The given information is not acceptable
        500:
          description: An internal error has occurred. Contact maintainer
